SELECT * FROM employees ORDER BY FIRST_NAME ASC;
SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY * 0.15 AS TAXES FROM employees;
SELECT SUM(SALARY) AS TOTALSALARY FROM employees;
SELECT MIN(SALARY) AS MINSALARY, MAX(SALARY) AS MAXSALARY FROM employees;
SELECT COUNT(*) AS TOTALRECORDS, AVG(SALARY) AS AVERAGESALARY FROM employees;
